-- ============================================================
-- SQL para criar tabela de usuários no Oracle
-- Execute no seu banco antes de usar o sistema de login
-- ============================================================

-- Tabela de usuários
CREATE TABLE dashboard_users (
  id            VARCHAR2(50)  DEFAULT SYS_GUID() PRIMARY KEY,
  username      VARCHAR2(100) NOT NULL UNIQUE,
  password_hash VARCHAR2(255) NOT NULL,
  full_name     VARCHAR2(200) NOT NULL,
  email         VARCHAR2(200),
  role          VARCHAR2(20)  DEFAULT 'viewer' NOT NULL,
  avatar        VARCHAR2(10),
  active        NUMBER(1)     DEFAULT 1 NOT NULL,
  created_at    DATE          DEFAULT SYSDATE,
  updated_at    DATE          DEFAULT SYSDATE,

  CONSTRAINT chk_role CHECK (role IN ('admin', 'viewer', 'manager'))
);

-- Tabela de preferências (vinculada ao usuário)
CREATE TABLE dashboard_preferences (
  user_id     VARCHAR2(50)  PRIMARY KEY,
  preferences CLOB,
  created_at  DATE DEFAULT SYSDATE,
  updated_at  DATE DEFAULT SYSDATE,

  CONSTRAINT fk_prefs_user FOREIGN KEY (user_id)
    REFERENCES dashboard_users(id) ON DELETE CASCADE
);

-- Tabela de log de acesso
CREATE TABLE dashboard_access_log (
  id         NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id    VARCHAR2(50),
  username   VARCHAR2(100),
  ip_address VARCHAR2(50),
  action     VARCHAR2(100),
  created_at DATE DEFAULT SYSDATE
);

-- ── Usuários iniciais ────────────────────────────────────────
-- ATENÇÃO: Gere os hashes corretos com o comando:
--   cd backend && npm run hash-password SuaSenha
--
-- Abaixo: senha 'admin123' e 'diretor123' (TROQUE EM PRODUÇÃO)

INSERT INTO dashboard_users
  (id, username, password_hash, full_name, email, role, avatar, active)
VALUES
  ('u001', 'admin',
   '$2a$10$AZQIGMVhRMqL/5onBJ7U8Ofl5l3H0xubzVnsfN4gtbjjNsARNCTT.',
   'Administrador', 'admin@empresa.com', 'admin', 'AD', 1);

INSERT INTO dashboard_users
  (id, username, password_hash, full_name, email, role, avatar, active)
VALUES
  ('u002', 'diretor',
   '$2a$10$mdsU6hBEtxeeqGlIm1TKIus6wBF3ti3eqM7mDO7lTyRs0YyvnZUf2',
   'Diretor Comercial', 'diretor@empresa.com', 'viewer', 'DC', 1);

INSERT INTO dashboard_users
  (id, username, password_hash, full_name, email, role, avatar, active)
VALUES
  ('u003', 'gerente',
   '$2a$10$mdsU6hBEtxeeqGlIm1TKIus6wBF3ti3eqM7mDO7lTyRs0YyvnZUf2',
   'Gerente de Vendas', 'gerente@empresa.com', 'manager', 'GV', 1);

COMMIT;

-- ── Verificar usuários criados ───────────────────────────────
SELECT id, username, full_name, role, active FROM dashboard_users;
